base_url: "https://www.saucedemo.com"

browser:
  name: "chromium"
  headless: false
  timeout: 30000
  viewport:
    width: 1280
    height: 720

test_data:
  valid_username: "standard_user"
  valid_password: "secret_sauce"
  invalid_username: "standard_use"
  invalid_password: "secret_sauce"

timeouts:
  default: 30000
  short: 5000
  long: 60000

screenshots:
  enabled: true
  on_failure: true
  path: "reports/screenshots"