name: Smoke Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      browser:
        description: 'Browser to run tests on'
        required: true
        default: 'chromium'
        type: choice
        options:
        - chromium
        - firefox
        - webkit

jobs:
  smoke-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('automation_framework/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      working-directory: automation_framework
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Install Playwright browsers
      working-directory: automation_framework
      run: |
        playwright install chromium
        playwright install-deps chromium
    
    - name: Create reports directory
      working-directory: automation_framework
      run: |
        mkdir -p reports/screenshots
        mkdir -p reports/videos
        mkdir -p reports/logs
        mkdir -p reports/allure-results
    
    - name: Run smoke tests
      working-directory: automation_framework
      env:
        BROWSER_NAME: 'chromium'
        HEADLESS: 'true'
        TEST_ENV: 'default'
      run: |
        pytest -v \
          -m "auth and smoke" \
          --alluredir=reports/allure-results \
          --html=reports/smoke_report.html \
          --self-contained-html \
          tests/
    
    - name: Generate Allure Report
      if: always()
      working-directory: automation_framework
      run: |
        allure generate reports/allure-results --clean -o reports/allure-report
    
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: smoke-test-results
        path: |
          automation_framework/reports/
        retention-days: 7
    
    - name: Upload screenshots on failure
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: smoke-test-screenshots
        path: automation_framework/reports/screenshots/
        retention-days: 3
